[any.drivers.aml_u_v]
type="aml"
title="AML U V"
url="http://localhost:30000/api/latest"
names = ["U", "V"]

[pellicle.drivers.motrona_terminal_voltage]
type="motrona_ax350"
title="Motrona terminal voltage"
url="http://127.0.0.1:22100/api/latest"

[pellicle.drivers.g64]
type="mirion_g64"
title="Mirion G64 Radiation"
url="http://127.0.0.1:22102/api/latest"

[pellicle.drivers.keithley]
type="keithley"
title="keithley"
url="http://127.0.0.1:22101/api/latest"

[pellicle.drivers.aml_x_y]
type="aml"
title="AML X Y"
url="http://localhost:20000/api/latest"
names = ["X", "Y"]

[pellicle.drivers.aml_det_theta]
type = "aml"
title = "AML Detector Theta"
url = "http://localhost:20000/api/latest"
names = ["Detector", "Theta"]

[pellicle.drivers.aml_phi_zeta]
type = "aml"
title = "AML Phi Zeta"
url = "http://localhost:20000/api/latest"
names = ["Phi", "Zeta"]

[pellicle.drivers.motrona_charge]
type = "motrona_dx350"
title = "Motrona Charge"
url = "http://localhost:20100/api/latest"

[pellicle.drivers.caen]
type = "caen"
title = "Caen"
url = "http://localhost:20200/api/latest"
detectors = [
	{"board"="33", "channel"=0, "identifier"="MD01", "bins_min"=0, "bins_max"=11264, "bins_width"=1024},
	{"board"="33", "channel"=3, "identifier"="MD04", "bins_min"=0, "bins_max"=11264, "bins_width"=1024},
	{"board"="33", "channel"=0, "identifier"="d01", "bins_min"=0, "bins_max"=11264, "bins_width"=1024},
	{"board"="33", "channel"=1, "identifier"="d02", "bins_min"=0, "bins_max"=11264, "bins_width"=1024},
]


[pellicle]
local_dir = "/tmp/ACQ/5_data"
remote_dir = "/tmp/ACQ/REM/_05_data"

