[pellicle.drivers.motrona_terminal_voltage]
type="motrona_ax350"
title="Motrona terminal voltage"
url="http://127.0.0.1:22100/api/latest"

[any.drivers.g64]
type="mirion_g64"
title="Mirion G64 Radiation"
url="http://127.0.0.1:22102/api/latest"

[pellicle.drivers.motrona_charge]
type = "motrona_dx350"
title = "Motrona Charge"
url = "http://localhost:20100/api/latest"

[pellicle.drivers.caen]
type = "caen"
title = "Caen"
url = "http://localhost:20200/api/latest"
detectors = [
	{"board"="33", "channel"=0, "identifier"="MD01", "bins_min"=0, "bins_max"=11264, "bins_width"=1024},
	{"board"="33", "channel"=3, "identifier"="MD04", "bins_min"=0, "bins_max"=11264, "bins_width"=1024},
	{"board"="33", "channel"=0, "identifier"="d01", "bins_min"=0, "bins_max"=11264, "bins_width"=1024},
	{"board"="33", "channel"=1, "identifier"="d02", "bins_min"=0, "bins_max"=11264, "bins_width"=1024},
]



